version = "2.0"
watch_list = ["literate/*.qmd"]

[[languages]]
name = "JavaScript"
identifiers = ["javascript", "js"]
comment = { open = "//" }

[[languages]]
name = "Observable JavaScript"
identifiers = ["ojs"]
comment = { open = "//" }

[[languages]]
name = "TypeScript"
identifiers = ["typescript", "ts"]
comment = { open = "//" }
