project:
  type: book
  output-dir: ../docs

book:
  title: "diffusion algorithms for bacteria"
  author: "Norah Jones"
  date: "8/20/2026"
  chapters:
    - index.qmd
    - adi.qmd
    - crankNicolson.qmd
    - analyticSolution.qmd
    - effective.qmd
    - thomasAlgorithm.qmd
    - initArrays.qmd
    - helpers.qmd
    - references.qmd

resources:
  - analyticSolution.js

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



