project:
  type: book
  output-dir: docs

book:
  title: "diffusion algorithms for bacteria"
  author: "Norah Jones"
  date: "8/20/2026"
  chapters:
    - index.qmd
    - markdown/package.qmd
    - markdown/adi.qmd
    - markdown/crankNicolson.qmd
    - markdown/analyticSolution.qmd
    - markdown/effective.qmd
    - markdown/thomasAlgorithm.qmd
    - markdown/helpers.qmd
    - markdown/references.qmd


bibliography: markdown/references.bib

format:
  html:
    theme:
      - cosmo
      - brand
