version = "2.4.0"

[[files]]                                                                       
source = "adi.qmd"                                                              
target = "../src/adi.js"                                                        
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "crankNicolson.qmd"                                                    
target = "../src/crankNicolson.js"                                              
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "analyticSolution.qmd"                                                 
target = "../src/analyticSolution.js"                                           
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "effective.qmd"                                                        
target = "../src/effective.js"                                                  
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "thomasAlgorithm.qmd"                                                  
target = "../src/thomasAlgorithm.js"                                            
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "initArrays.qmd"                                                       
target = "../src/initArrays.js"                                                 
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "helpers.qmd"                                                          
target = "../src/helpers.js"                                                    
language = "javascript"                                                         
                                                                                
[[files]]                                                                       
source = "indexModule.qmd"                                                      
target = "../src/index.js"                                                      
language = "javascript"          
